### ISSUE TITLE
Add bootstrap to the partner app

### ISSUE THREAD

**Issue by davidshr10** [rubyforgood/partner#10]
We will need to add the bootstrap gem to the Gemfile (https://github.com/twbs/bootstrap-rubygem)

We have a basic login form we would like to apply bootsrap styling (/partners/sign_in)

**Comment by segunadeleye** [comment]
I would love to pick up this issue and work on it.

**Comment by davidshr10** [comment]
> I would love to pick up this issue and work on it.

@segunadeleye Hey looks like someone already made a PR to it. I've created a new issue to apply css styling to the login form if you're interested! https://github.com/rubyforgood/partner/issues/14

**Comment by segunadeleye** [comment]
@davidshr10 I later realised someone already picked it up. I am just seeing the message about the other issue. I think someone also picked that up but yet to raise a PR. Perhaps I could still pick it up.
