### ISSUE TITLE
Add in the concept of families and children

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/partner#101]
[SCDB Client Application-2017 update 2 (1).pdf](https://github.com/rubyforgood/partner/files/3025186/SCDB.Client.Application-2017.update.2.1.pdf)

See above. We need to be able to collect family information and child information.
In addition to the information listed here we should also collect if the family is a veteran family.

**Comment by kkuchta** [comment]
We have the "concept" of this done in the `families` branch - a Family and Child table.  We're still in the process of adding a usable UI for actually *adding* them to the database.
