### ISSUE TITLE
Make Requests by Child

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/partner#102]
We need a second type of request.

We need to allow for the requests by children -- a user based request where, rather than selecting a bulk number of diapers, they select the children who they are requesting diapers for in a given month and the system auto completes the request. For example, they have 10 kids who wear size 1 diapers, then the system will automatically request 500 size 1 diapers in the request since the diaper bank gives 50 size 1 per child.

We should have an active flag on each child and on the checklist of children all the children who are active are automatically set to request for.

**Comment by kkuchta** [comment]
This is mostly-functional in the `families` branch:

- [x] UI to select children (/family_requests/new)
- [x] Submitting creates a FamilyRequest in the partner's db
- [x] Submitting makes a call to the bank's api (to a new endpoint that creates a request from a list of children + item types)
- [ ] Create a PartnerRequest in the partner's db based on the response to that api
- [ ] Actually add a link to this page somewhere.

Also todo are specs and any UI cleanup we want.

**Comment by kkuchta** [comment]
![Apr-01-2019 11-12-19](https://user-images.githubusercontent.com/820965/55349861-91755680-546f-11e9-8c85-a16921655adf.gif)
(The "Item Needed" column is the id of the item)
