### ISSUE TITLE
Update partner request form to require at least 1 item

### ISSUE THREAD

**Issue by joshleichtung** [rubyforgood/partner#111]
Currently, a partner can make a request without actually including any items. There should probably be validations around this, both in the form and perhaps in the data model. 

<img width="1209" alt="Screen Shot 2019-03-31 at 4 51 26 PM" src="https://user-images.githubusercontent.com/4044653/55353634-ab676700-5478-11e9-9700-70b2c62dbefb.png">
The above is a valid submission but should not be.

**Comment by Randond** [comment]
Hello, I am a student from Loyola, I would like to work on this issue.  I cannot assign it to myself as we are only allowed to assign issues to ourselves that are in the Loyno team.  As a result, I will make a copy of the issue over there and be working on it.  I will inform you how this issue progresses.

**Comment by seanmarcia** [comment]
Hey @joshleichtung and @Randond I think they should be able to make requests without items provided they have something in the comments. I can see a situation where a partner might send a request with just comments if they were looking for non-standard items. A comment like the following seems possible - "We are helping a teenage girl who was kicked out of her house and are trying to source her a crib, car seat, and a comfortable chair for her to sit in with the baby."

**Comment by Randond** [comment]
@joshleichtung @seanmarcia I'm having a little trouble with this issue.  Do you think you could do a pairing session with me?

**Comment by seanmarcia** [comment]
@Randond I'm a little packed this weekend but may have some time Monday. Can you push a branch with what you've done so far? I may be able to offer some suggestions!

**Comment by Randond** [comment]
Here is a link to a pull request I just made. https://github.com/loyno-mathcs/partner/pull/19

**Comment by seanmarcia** [comment]
Hey @Randond I took a look and the path you're going down could work but I think there is a simpler solution using a rails validation.
You can take a read [here](https://guides.rubyonrails.org/active_record_validations.html) about rails validations. I think something like this should probably do what you're looking for:
`validates :items, presence: {unless: :comments?}`
Just customize and some tests to confirm it and we should be good to go!

**Comment by Randond** [comment]
@seanmarcia created new pull request https://github.com/loyno-mathcs/partner/pull/20

**Comment by benreyn** [comment]
It looks like https://github.com/loyno-mathcs/partner/pull/20 got merged. @seanmarcia @mdworken @armahillo Im going to cherry pick that commit so that..

1. @Randond gets credit for his contribution, and...
2. We can close out this issue

**Comment by benreyn** [comment]
Fixed in #130
