### ISSUE TITLE
Pickup Sheets

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/partner#122]
# Summary

Partners often make a list of people that will be picking up diapers and then they enter them into spreadsheets that the print out, mark off when people pick up their supplies and then re-enter that information back into a spreadsheet. We need to create pick up sheets linked to family requests that allow partners to mark off which of their clients have picked up their monthly diaper distribution. This will provide a huge benefit for the partners, save them a lot of time, and provide them with useful tracking information. 

# Criteria for Completion

- [x] Create pick up sheets that are created at the same time as a family request and linked to from the request index page.
- [x] Pickup sheets should contain a list of all the kids from request with a "Picked Up" toggle (like the one of the family request) that can be flipped when the family picks up their diapers.
- [x] The pickups should also be linked to the child and on the child show page a list of past pick ups can be viewed.
- [x] They should be able to select who picked up the diapers. Either the guardian or an authorized pick up recipient #127 

# Inspiration Pickup Report

<img width="1166" alt="Screen Shot 2019-07-26 at 10 34 22 AM" src="https://user-images.githubusercontent.com/1443346/61959240-fc9fe700-af90-11e9-8557-4b2d9e57fc09.png">

# Bonus Points

- [ ] Add in print friendly stylings for the partners who want to print it out.

**Comment by mlpinit** [comment]
Additional requirements:

- [ ] Account for differences in distributions (different item size, different item count)

**Comment by benreyn** [comment]
Completed in a series of PRs from @mlpinit. Thanks @mlpinit!
