### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by benreyn** [rubyforgood/partner#126]
Issue templates that might be useful:
- [ ] Bug report
- [ ] Feature request
- [ ] Feature spec (This should be the template that all feature requests that morph into. Having a template will let us make a new issue once we have a spec or convert the existing feature request depending on our need for that feature. Sometimes features will get requested and fleshed out in a live or google hangouts stakeholder meeting and we can use this template in those cases.)

**Comment by cedarfall** [comment]
@seanmarcia Can I work on this?

**Comment by seanmarcia** [comment]
It's yours!

**Comment by cedarfall** [comment]
@seanmarcia Will the default templates be alright or should I change them? Also what fields would you require for the Feature spec template?

**Comment by benreyn** [comment]
@cedarfall, I think the default templates are a good enough start.
