### ISSUE TITLE
Login Form Styling

### ISSUE THREAD

**Issue by davidshr10** [rubyforgood/partner#14]
Please follow the USDS guidelines for the buttons, input fields, labels and colors.

https://designsystem.digital.gov/components/form-controls/

I've attached a design mockup for this. 
![screen shot 2018-10-04 at 6 50 32 pm](https://user-images.githubusercontent.com/1936038/46507467-9df15d00-c806-11e8-8d93-282e6601bc35.png)

Finally, If you're really interested in design, please look into atomic design. It's a great chance to apply these principles when creating reusable templates and styling. More information can be found here (http://bradfrost.com/blog/post/atomic-web-design/)

If you have any questions, [Check our slack](https://rubyforgood.herokuapp.com/)

**Comment by davidshr10** [comment]
@raul1991 All yours! If you have any questions, hop over to [our slack](https://rubyforgood.herokuapp.com/)

**Comment by seanmarcia** [comment]
Hey @raul1991 any updates on this? We're doing a hack day tomorrow and will try to pick this up if you haven't made any progress!

**Comment by raul1991** [comment]
Yes please go ahead. I couldn't look into it.

>
