### ISSUE TITLE
Test Coverage: Children Controller

### ISSUE THREAD

**Issue by chaserx** [rubyforgood/partner#151]
At 59% coverage, we should increase test coverage for the Children Controller with **request specs**

<img width="1792" alt="Screen Shot 2019-07-28 at 9 35 26 AM" src="https://user-images.githubusercontent.com/7292/62007411-0ead9100-b11b-11e9-916f-615d213d73a3.png">

**Comment by EmersonManabuAraki** [comment]
PR with the test: #179
