### ISSUE TITLE
DB seed fails due to invalid attributes

### ISSUE THREAD

**Issue by samudary** [rubyforgood/partner#162]
The DB seed failed upon setting up the codebase for the first time due to a `ActiveModel::UnknownAttributeError: unknown attribute 'email' for Partner.` It appears the `email` attribute and the Devise attribute `password` were removed from the `Partner` model in [this commit](https://github.com/rubyforgood/partner/commit/b136e0781b8b19060288599823d6ba369f76849f). Removing those attributes should fix the seed file.

**Comment by benreyn** [comment]
Good catch! Thanks for logging this @samudary!
