### ISSUE TITLE
Rails 6!

### ISSUE THREAD

**Issue by chaserx** [rubyforgood/partner#167]
Rails 6 is out. 

Should we? I think it won't be too bad

**Comment by benreyn** [comment]
The thing that Im concerned about is the "webpacker by default" business. (We've been through this at my day job, and it can be a bit of a pain)

**Comment by kdreyeroren** [comment]
If we're confident about our test coverage, it's always worth shoving it in and seeing how many tests fail!

**Comment by renanbona** [comment]
Can I work on this issue?

**Comment by benreyn** [comment]
I would coordinate with @edwinthinks. I believe he started a new effort to upgrade to Rails 6. (its possibly already ready? #288)

**Comment by edwinthinks** [comment]
> I would coordinate with @edwinthinks. I believe he started a new effort to upgrade to Rails 6. (its possibly already ready? #288)

@benreyn possibly. The tests went green but I have yet to test it locally. I'll follow up here :)

**Comment by edwinthinks** [comment]
Update here, I've run the update (correctly this time) and tested the branch locally. So far things seem to work. I could use some extra eyes on this one  - https://github.com/rubyforgood/partner/pull/288
