### ISSUE TITLE
Add Styling to Partner Editing

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/partner#223]
# Summary
Currently the partner editing has fairly basic form fields and it could be made much nicer and easier for the diaper bank partners to work with.

Anyone with UI/UX skills could probably make some huge improvements on this. Some of the things that come to mind are sliders for the population %'s, nicer checkbox options, and so on. 

Any help here would be greatly appreciated!

**Comment by prabes** [comment]
I went through the app and I found some of the components like checkbox, % slider, choose file to be enhanced. 
Just to be sure, were you talking about these fields to be sliders? 
 
![hacktober](https://user-images.githubusercontent.com/22254625/66719271-664fc480-ee0d-11e9-9509-c015c512f907.jpg)


I'm on it.

**Comment by seanmarcia** [comment]
Yes, those were the fields I was talking about! Thanks for taking this issue!

**Comment by prabes** [comment]
I found `bootstrap.min.css` here `app/stylesheets` , I was wondering why you were using this?

**Comment by seanmarcia** [comment]
Honestly, I'm not sure. We sort of shoved the current theme in there. For reference, here is the current theme we're using: https://github.com/pratikborsadiya/vali-admin

**Comment by keithrbennett** [comment]
Would these sliders support inputting the value as a number on the keyboard in addition to sliding? (I hope so.)

**Comment by prabes** [comment]
I am trying to upgrade your UI using bootstrap gem @seanmarcia .
And yeah, The slider will support the number inputs too along with slider. 
Working On It.
