### ISSUE TITLE
On the Family/show page, list all the children that belong_to the family

### ISSUE THREAD

**Issue by benreyn** [rubyforgood/partner#250]
### Summary

On the `families#show` page we should be listing all of the children that are associated with that family.

### Criteria for completion

On the `families#show` page, add a section below "Authorized Family Members" for "Children" and list all of the children that are associated with the family. We should list the name, age, and gender of the child.

**Comment by sarslanoglu** [comment]
@benreyn I can work on this

**Comment by benreyn** [comment]
Thank you @sarslanoglu ! Please reference this issue when you make your pull request.

**Comment by sarslanoglu** [comment]
@benreyn Something like this one is good, or should i try to find a way to show age like just one integer

<img width="1177" alt="Screen Shot 2019-10-24 at 23 57 27" src="https://user-images.githubusercontent.com/10260283/67524831-2fee3100-f6ba-11e9-9fe5-2343c6f07260.png">

**Comment by benreyn** [comment]
That’s perfect @sarslanoglu! Thanks! Go ahead and submit a PR and I can review it!
