### ISSUE TITLE
Add tests from controllers

### ISSUE THREAD

**Issue by gabrielbaldao** [rubyforgood/partner#268]
**Description:**
I think we can improve this project writing more tests.

**Requirements:**
I was thing about start write some tests to:
- [x] children_controller_spec.rb
- [x] families_controller_spec.rb
- [x] partner_requests_controller_spec.rb
- [x] partners_controller_spec.rb
- [x] static_controller_spec.rb
- [ ] api_controller_spec.rb
- [ ] authorized_family_members_controller_spec.rb
- [ ] child_item_requests_controller_spec.rb
- [ ] dashboard_controller_spec.rb
- [ ] family_requests_controller_spec.rb
- [ ] pickup_sheets_controller_spec.rb
- [ ] users_controller_spec.rb

**Implementation Details:**
We can write one a one

**Comment by DouglasLutz** [comment]
Can I work on  `users_controller_spec.rb`?

**Comment by TCsTheMechanic** [comment]
May I work on `static_controller_spec.rb`?

**Comment by gabrielbaldao** [comment]
Please, go ahead, @DouglasLutz  @TCsTheMechanic

**Comment by benreyn** [comment]
I really appreciate the enthusiasm on this issue everyone! Thanks for bringing it up @gabrielbaldao, and thanks for diving in @DouglasLutz and @TCsTheMechanic 

I think I should mention though, that I dont really have an interest in adding a dependency on `rails_controller_testing` and moving back in the direction of controller tests over requests specs. 

My general philosophy on this is that controller tests were deprecated by the rails core team for a reason and that anything we are testing with a controller tests we can test better with a request spec. My feelings around this are pretty similar to the rails core team. much of what you would test in a controller tests that wouldnt fit in a requests spec is reaching too much into the internals of the controller. I don't need to know that an instance variable was assigned, I just need to know that I get successful response.

Is there any way we could focus this work on standardizing on request specs and not moving back in the direction of unit tests for controllers?

**Comment by gabrielbaldao** [comment]
I understand you @benreyn, so I create the #271 just to fix about my last pr #265 and #266, because in there i did create tests on controller, what you think?

**Comment by m-pereira** [comment]
Can I work on `authorized_family_members_controller_spec.rb`?

**Comment by benreyn** [comment]
Feel free @m-pereira. Just try to avoid the `rails-controller-testing` gem and stick to request specs.
