### ISSUE TITLE
Move the "Add Family" button to the top of the page on families/index

### ISSUE THREAD

**Issue by benreyn** [rubyforgood/partner#276]
We received the feedback that its frustrating to have to scroll to the bottom of the page to click "Add family" every time a user wants to make a new family record. This would make more sense at the top of the page anyway.

**Comment by sarslanoglu** [comment]
@benreyn I can work on this one

**Comment by Aliciawyse** [comment]
Hey @benreyn and @sarslanoglu, is this still up for grabs?

**Comment by sarslanoglu** [comment]
@Aliciawyse Completely forgot this one. Feel free to work on it
