### ISSUE TITLE
Improve the UX of onboarding partners to be more clear.

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/partner#280]
# Summary

Currently, partners are 'thrown' into the application on first use without much context or guidance on what to do. Once they set their password via the invitation email, they are presented with the dashboard. What they may not know is that they have to access the `Edit My Organization` to fill out the information to continue with onboarding.

Let's figure out a way to guide partners through onboarding and implement it.

** I encourage the assignee to share their solution with the diaper channel to get alignment **

**Comment by samudary** [comment]
@edwinthinks I see that the "Ruby for Good 2020" label has been removed. Is this free for anyone to pick up? If yes, I can take it

**Comment by edwinthinks** [comment]
@samudary yep you can take this! Let me change the description.

**Comment by edwinthinks** [comment]
@samudary I apologize but, I am going to close this issue. We are likely going to think internally about how we are going to revisit our thoughts on UX for our partners. And having that alignment would be an important step :).

If you've worked on this or had thoughts on this. Please share it with us (myself or @designbygia) in this issue or via RFG slack
