### ISSUE TITLE
Safely get rid of typo

### ISSUE THREAD

**Issue by Aliciawyse** [rubyforgood/partner#286]
**Describe the bug**
Take a look here https://github.com/rubyforgood/partner/blob/master/app/models/family.rb#L44 and notice `guardian_health_insuranceb`. That letter b at the end appears to be a typo. This is an assumption though based on the family model's [attributes](https://github.com/rubyforgood/partner/blob/master/app/models/family.rb#L19) and the [to_csv method](https://github.com/rubyforgood/partner/blob/master/app/models/family.rb#L82). Need to confirm if it's a typo and if we fix it, we need to make sure the typo isn't used elsewhere in the app.

**Comment by edwinthinks** [comment]
@Aliciawyse I think this is a pretty small change that we could probably fix. @benreyn thoughts? Just making sure that users weren't working on the assumption and relying on the erroneous csv header.

**Comment by Aliciawyse** [comment]
Yeah I can fix this really quick.

**Comment by Aliciawyse** [comment]
Also, I think it's safe to change. I _believe_ it's only being used to generate a csv as seen https://github.com/rubyforgood/partner/blob/master/app/views/families/index.csv.erb.
