### ISSUE TITLE
Error when submitting diaper request

### ISSUE THREAD

**Issue by SCDB** [rubyforgood/partner#293]
Hi there! One of our partner agencies, Crossroads Harrison, is getting an error message with 3 reasons why they can't submit an order to us. 

![IMG-0399](https://user-images.githubusercontent.com/34867963/80002322-7bc53b80-848d-11ea-895d-b94cd404fd0f.JPG)
![IMG-0068](https://user-images.githubusercontent.com/34867963/80002327-7cf66880-848d-11ea-9c50-5788c31ea5a8.JPG)

As far as we can tell this hasn't happened to them before and hasn't happened to any other agencies. 

Megan

**Comment by benreyn** [comment]
It looks like (to me) from that screenshot, that the last item in the list "Wipes (Baby)" has no quantity input on the request. My hunch is that putting a quantity in that field and resubmitting should allow the request to go through.

**Comment by SCDB** [comment]
Thank you!! We'll have them try that out.

Megan Fischer
CEO & Founder
Sweet Cheeks Diaper Bank
1400 State Ave
Cincinnati, OH 45204
513-402-1450 Ext. 101
www.sweetcheeksdiaperbank.org
