### ISSUE TITLE
Child Show Page Not Showing Correct Distribution Details

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/partner#329]
On the child#show page we display the history of Requested Items by that child. Unfortunately it displaying the incorrect item in the history.

We need to update things so it shows the correct item.

![Requested Items](https://user-images.githubusercontent.com/667909/84575829-2e26ca00-ad7e-11ea-8a7b-03592b193177.jpg)

**Comment by edwinthinks** [comment]
I can take this one. I think I see what is the problem here
