### ISSUE TITLE
Only Show Unique Zip Codes Served

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/partner#344]
On the dashboard we display the zip codes served by the partner. We shouldn't display duplicate zip codes and only the unique ones.

![area_served](https://user-images.githubusercontent.com/667909/85240974-2a431980-b408-11ea-8eac-c0fae45b9b07.jpg)

**Comment by samudary** [comment]
I got this! @seanmarcia

**Comment by seanmarcia** [comment]
Awesome, thanks!
