### ISSUE TITLE
Fix Recertification Mailer

### ISSUE THREAD

**Issue by designbygia** [rubyforgood/partner#383]
## Summary

Partner recertification emails have a couple of issues that need to be resolved, please:

* Change the subject line to title case
* Change the default email _from_ address to info@diaper.app
* Change this text:  `Please follow this link to verify your agency's information: <%= edit_partner_url(@partner) %>.` to `Please log in to your account at https://partner.diaper.app/`

If you have any questions, please contact me (Gia) in the [Ruby for Good Slack](https://rubyforgood.herokuapp.com). 

### Criteria for Completion

- [ ] Subject line is changed to title case. 
- [ ] Default _from_  email  address is changed to info@diaper.app.
- [ ] Email text and link has been updated. 
- [ ] All relevant tests for this functionality.

**Comment by Aliciawyse** [comment]
Hey 👋 I can take this up.
