### ISSUE TITLE
Rubocop Defaults

### ISSUE THREAD

**Issue by designbygia** [rubyforgood/partner#436]
Rubocop is making our travis logs pretty spamming because we don't have defaults set for some of the newer cops. We need someone to look at the missing cops, add them to our .rubocop.yml file.

Alternatively, if someone wanted to remove rubocop and all its artifacts and instead move us to the standard gem that would also be a good solution.

This relates to https://github.com/rubyforgood/diaper/issues/1902 and we should be using the same defaults.

**Comment by aaron-contreras** [comment]
I'll take care of this.

**Comment by aaron-contreras** [comment]
On cloning the repo, running `./bin/setup` and running `bundle exec rake` I get 8 example failures. Is there a step missing in the Contributing guide?

**Comment by aaron-contreras** [comment]
Is this repository "hacktoberfesty"?
