### ISSUE TITLE
Dashboard and sidebar language change

### ISSUE THREAD

**Issue by designbygia** [rubyforgood/partner#440]
### Summary 
We have period supply and incontinence supply organizations using our application so it doesn't make sense to have diaper specific language. Let's make it more generic. Let's change the language away from diapers to essentials on the dashboard.

#### Criteria for Completion
- [ ] Rename sidebar item from `Diaper Requests` to `Essentials Requests`
- [ ] Rename dashboard header from `Diaper Request History` to `Essentials Request History`
- [ ] Rename header in the history from `Your recent diaper requests` to `Your recent essentials requests`
- [ ] Rename button from `Create new Bulk Diaper Request` to `Create new Bulk Essentials Request`
- [ ] Rename button from `Create New Family Diaper Request` to `Create New Family Essentials Request`
- [ ] Update any tests that require updating

**Comment by ErinClaudio** [comment]
I would like to work on this, please.
