### ISSUE TITLE
Move Essentials Requests To Card With Description

### ISSUE THREAD

**Issue by designbygia** [rubyforgood/partner#453]
### Summary
We received some feedback from a user that now that we have three kinds of requests it is easy for users to click the wrong one without knowing what a specific request is for. Let's move the request buttons on the dashboard into their own card and on the requests page they are already on their own card so let us keep them there but add more information to the request.

#### Criteria for completion
- [ ] Create a card on the dashboard above the Essentials Request History with the label `Request Essentials`, the card should only be visible to verified partners.
- [ ] Move the buttons `Create New Bulk Essentials Request`, `Create New Family Essentials Request` and add the button `Create New Individuals Essentials Request` to the card.
- [ ] Add the label `Request Essentials` to the card on the requests page that already contains the three buttons.
- [ ] On the two cards add the description for `Create New Bulk Essentials Request` - Use this type of request when you want to specify the number of diapers, period supplies, and other essentials. Example - 1000 Size 1 Diapers, 500 Tampons, etc.
- [ ] On the two cards add the description for `Create New Family Essentials Request` - Use this type of request when you you are using the children and family functionality and are identifying the specific children you are requesting for.
- [ ] On the two cards add the description for `Create New Individuals Essentials Request` - Use this type of request when you want to just request by the number of individuals in a specific category. Example - 10 individuals for Size 1 diapers, 5 individuals need tampons, etc.
Use your best judgement on how to display the buttons and the description. You can use 3 columns with a button and description in each, a list with the button and description, or something else. Whatever you think is best!

**Comment by ErinClaudio** [comment]
Can I have a try at this?

**Comment by designbygia** [comment]
Absolutely @ErinClaudio! Also, please ping @edwinthinks on slack with any additional questions. Thank you! :O)

**Comment by ErinClaudio** [comment]
Yup!!

**Comment by meg-gutshall** [comment]
@seanmarcia Should this issue be closed? See PR #458
