### ISSUE TITLE
[Question] Could partners have a place to submit impact stories with an option to upload images?

### ISSUE THREAD

**Issue by armahillo** [rubyforgood/partner#47]
From a diaperbank:

> A place for partners to submit impact stories with an option to upload images.  Collecting stories is important to us so we give them a place to submit them on our "agency portal" page on our website. 

(This may or may not be in-scope for this project, but I said I would pass it along!)

**Comment by edwinthinks** [comment]
This appears to have come up again in the recent https://github.com/rubyforgood/partner/issues/352. I'll close this issue in favor of the other as the other seems to have some great context 👍
