### ISSUE TITLE
Implement a rest endpoint `/register` that receives a POST request from the diaper app

### ISSUE THREAD

**Issue by davidshr10** [rubyforgood/partner#5]
This deals with registering a partner (user) through the diaper app. The process of registration happens when the diaper app sends a POST request to the /register endpoint as described below.

`When` The app receive a registration request on the `/api/v1/register` route
`Then` the system will create a new partner
`And` the system will email the partner with the registration link

The /register POST request includes the following payload:
```
{
organization_id: string,
partner_id: string,
email: string
}
```
Tests should be included that makes sure the registration link is sent. Docs on how to add rspec tests for action mailer is found here
1. https://relishapp.com/rspec/rspec-rails/docs/mailer-specs
2. https://www.lucascaton.com.br/2010/10/25/how-to-test-mailers-in-rails-with-rspec/

**Comment by mclintprojects** [comment]
I'll be working on this issue.

**Comment by eyewritecode** [comment]
Hi @davidshr10, i see that no one is assigned to this yet! Can i start working on it already?

**Comment by denysmedynskyi** [comment]
Can I take this?
