### ISSUE TITLE
Remove all json endpoints that are not in the `API::` namespace

### ISSUE THREAD

**Issue by armahillo** [rubyforgood/partner#50]
There appears to be replicated code in both the normal `partners_controller.rb` and the API path code. If this is indeed replicated, then the general namespace controller code can be removed.

**Comment by benreyn** [comment]
It looks like this isnt exactly replicated, but that the generic `partners_controller.rb` was generated from a rails scaffold, which includes a json response. Lets confirm that these endpoints arent being used for anything, and then ✂️ ✂️

**Comment by benreyn** [comment]
I did a quick look see through the diaper and partner codebases, and I cant see that the `.json` endpoints that are NOT namespaced under `API::` are used anywhere. I think its safe to delete them.

**Comment by benreyn** [comment]
Closed in #143
