### ISSUE TITLE
Fix either `seeds.rb` or the `README.md` regarding default users

### ISSUE THREAD

**Issue by armahillo** [rubyforgood/partner#52]
Currently the `README.md` file indicates that the default users are `org_admin1@example.com` and `user1@example.com` but the defaults created by the `seeds.rb` file are `leslie@example.com` and `pending@example.com`.

I love Parks & Recreation, but it might be better to use a generic email (the rest of the Partner details are probably fine though). :)

**Comment by chaserx** [comment]
🤚 I did that. I'll fix it up. 

![andy_monkeying](https://user-images.githubusercontent.com/7292/48667925-c7f99880-eaaf-11e8-9e75-d256d8f56c7b.gif)
