### ISSUE TITLE
Update Partner Json Payload

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/partner#57]
In our `partner.rb` model we have an export_json method for sending information to the diaper app. This method was created before we had implemented active storage and the uploading of `proof_of_partner_status, proof_of_form_990, and documents`.

We need to add links to those files in the payload we are sending to the diaper app so the diaper banks can view them.

For bonus points, create a PR in the Diaper app that adds view links to these files they will now be receiving.

**Comment by chaserx** [comment]
I'll take a crack at this.

**Comment by chaserx** [comment]
> For bonus points, create a PR in the Diaper app that adds view links to these files they will now be receiving.

For the bonus points section: I don't yet see the how diaper admin user flows to the partner approval page, but I was able to find the approval view. https://github.com/rubyforgood/diaper/pull/643
