### ISSUE TITLE
Partner can login to the partner app

### ISSUE THREAD

**Issue by davidshr10** [rubyforgood/partner#6]
We already have a partner user setup. We are using devise for authentication. The partner should be able to login and be redirected to a `profile` page where they are shown the following fields with their own information:

```
1. name
2. address
3. website
4. diaper_bank_id
5. diaper_partner_id
6. partner_status
```

`Given` a partner exists in the system
`And` has activated their account
`When` the partner goes to the home page
`Then` the partner sees the login form
`And` the partner can fill in the username and the password

`Given` the partner has an activated account
`When` the partner clicks login
`Then` the partner will be redirected to the home page
`And` the partner can edit and update their profile

**Comment by eyewritecode** [comment]
Hi @davidshr10 @seanmarcia can i work on this?!

**Comment by davidshr10** [comment]
@eyewritecode It's all yours. Your starting point is the `/partners/sign_in`. Good luck and reach out if you have any questions. You can find help [on slack](https://rubyforgood.herokuapp.com)

**Comment by eyewritecode** [comment]
Alright! Thanks! I'm on it
