### ISSUE TITLE
Partner Requests Only Show Active Items

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/partner#63]
Many diaper banks do not distribute all of the canonical items, and instead only distribute a subset. We should grab the the active items from the diaper bank and only allow the partner to make requests containing those items.

This issue requires modifying both the diaper and partner repos. A possible flow would be:
- [ ] Create an api endpoint on the diaper app to display the items that particular organization distributes.
- [ ] When making requests, pull in the items and only allow the partner to make requests from that list.

Something that may be helpful is that as of Ruby 2.5 hash now has the `slice` method. So you can slice out the values you want to keep. So if you have an array of valid items you could `POSSIBLE_ITEMS.slice(*valid_items)

I spent 20 minutes or so spiking this out a little on the `valid_items` branch (on both repos.) Feel free to use that as a starting point (or not.)

**Comment by seanmarcia** [comment]
This seems like a @chaserx issue ;)

**Comment by chaserx** [comment]
aw yeah.
