### ISSUE TITLE
Approved partner can fill out requests for diapers to their diaper bank partner

### ISSUE THREAD

**Issue by davidshr10** [rubyforgood/partner#8]
We need to create a new form for a partner to fill out so they can request for diapers from their diaper banks. 

The form will have labels to show the current partner's name.
The form will have the following input fields:

```
comments: string,

# The partner can click `Add an item` which will create a new row with 
the following information:

request_item: select dropdown,
quantity: number
```

`Given` the partner has filled out the form
`When` the partner clicks `Submit for Review`
`Then` the system will submit the form information to the diaper app

This will send a post request to the diaper app at `/api/v1/partner_requests`. Here is an example payload:
```json
{
    "request": {
        "partner_id":5,
        "organization_id":1,
        "comments":"Lots and lots of comments",
        "request_items":
            {
            "k_size1":100,
            "k_size2":200,
            "k_size3":200,
            "k_size4":200,
            "k_size5":222,
            "k_size6":444
            }
    }
}
```

**Comment by seanmarcia** [comment]
The for reference, the request will be hitting this controller: https://github.com/rubyforgood/diaper/blob/master/app/controllers/api/v1/partner_requests_controller.rb

**Comment by cesargralmeida** [comment]
I would like to take a try at this one :)

**Comment by seanmarcia** [comment]
Awesome! Thanks for taking this on!

**Comment by seanmarcia** [comment]
Hey @cesargralmeida I thought it might be helpful for you to have a list of the different items that can be requested as well as the keys that the partner app is expecting:
```
    "adult_lxl" => "Adult Briefs (Large/X-Large)",
    "adult_ml" => "Adult Briefs (Medium/Large)",
    "adult_sm" => "Adult Briefs (Small/Medium)",
    "adult_xxl" => "Adult Briefs (XXL)",
    "cloth" => "Cloth Diapers (Plastic Cover Pants)",
    "disposable_inserts" => "Disposable Inserts",
    "k_newborn" => "Kids (Newborn)",
    "k_preemie" => "Kids (Preemie)",
    "k_size1" => "Kids (Size 1)",
    "k_size2" => "Kids (Size 2)",
    "k_size3" => "Kids (Size 3)",
    "k_size4" => "Kids (Size 4)",
    "k_size5" => "Kids (Size 5)",
    "k_size6" => "Kids (Size 6)",
    "k_lxl" => "Kids L/XL (60-125 lbs)",
    "pullup_23t" => "Kids Pull-Ups (2T-3T)",
    "pullup_34t" => "Kids Pull-Ups (3T-4T)",
    "pullup_45t" => "Kids Pull-Ups (4T-5T)",
    "k_sm" => "Kids S/M (38-65 lbs)",
    "swimmers" => "Swimmers",
    "adult_cloth_lxl" => "Adult Cloth Diapers (Large/XL/XXL)",
    "adult_cloth_sm" => "Adult Cloth Diapers (Small/Medium)",
    "cloth_aio" => "Cloth Diapers (AIO's/Pocket)",
    "cloth_cover" => "Cloth Diapers (Covers)",
    "cloth_prefold" => "Cloth Diapers (Prefolds & Fitted)",
    "cloth_insert" => "Cloth Inserts (For Cloth Diapers)",
    "cloth_swimmer" => "Cloth Swimmers (Kids)",
    "adult_incontinence" => "Adult Incontinence Pads",
    "underpads" => "Underpads (Pack)",
    "bed_pad_cloth" => "Bed Pads (Cloth)",
    "bed_pad_disposable" => "Bed Pads (Disposable)",
    "bib" => "Bibs (Adult & Child)",
    "diaper_rash_cream" => "Diaper Rash Cream/Powder",
    "cloth_training_pants" => "Cloth Potty Training Pants/Underwear",
    "wipes" => "Wipes (Baby)"
```
Plus the comments field! :)

**Comment by cesargralmeida** [comment]
Hey, just a little RFC
https://github.com/cesargralmeida/partner/commit/5dc12677b1e15d5aa95fecd96b997b7ef2badb20
Just wondering if it is a good direction i am taking. Any feedback is appreciated

**Comment by seanmarcia** [comment]
Hey @cesargralmeida The direction looks good so far! I need to look up how cocoon works but it seems like you're on the right track. I think you'll need a show and index action as well (scoped to the partner) so they are able to see the requests they've made in the past.

**Comment by seanmarcia** [comment]
Hey @cesargralmeida any further updates?
