### ISSUE TITLE
Improve content of Partner Invitation email

### ISSUE THREAD

**Issue by armahillo** [rubyforgood/partner#80]
@pdxdiaperbank sez:
> ...the email itself: This is the view from the inbox. Can we remove: "This is a preheader text. Some clients will show this as a preview..." and change it to be something else? Maybe the first sentence in the body of the email?

There is some placeholder (preheader) text that is showing up in the e-mail preview:
![2](https://user-images.githubusercontent.com/20074085/51790175-8e47ac80-2146-11e9-8c9b-f96dd00aef8c.png)

@pdxdiaperbank sez:
> This is the body of the email. I circled a couple spelling errors. The yellow highlighted portion is my question: Can the partner organization ALREADY submit their diaper requests through PartnerBase? If not, maybe it shouldn't state this yet?

![3](https://user-images.githubusercontent.com/20074085/51790518-411a0980-214b-11e9-9074-dcfabbd41cbf.png)

The text in both cases is found in: 
 * `/app/views/mailer/invitation_instructions.html.erb`
 * `/app/views/mailer/invitation_instructions.text.erb`

# Criteria for Completion

 - [ ] Preview text either removed or changed to a short notice about the contents of the email
 - [ ] Spelling errors corrected

**Comment by Nirvikalpa108** [comment]
I will work on this @armahillo. Thanks ❤️
