### ISSUE TITLE
update POSSIBLE_ITEMS with X-Small/Small Adult Briefs

### ISSUE THREAD

**Issue by chaserx** [rubyforgood/partner#85]
referencing https://github.com/rubyforgood/diaper/issues/630 where we added a new cannonical item for X-Small/Small Adult Briefs we just need to update the hash of POSSIBLE_ITEMS here too. 

https://github.com/rubyforgood/partner/blob/master/config/initializers/01_constants.rb#L1

**Comment by chaserx** [comment]
@Nirvikalpa108 this corresponds to the work you did in Diaperbase.

**Comment by Nirvikalpa108** [comment]
Thank you @chaserx, I'll give it a go! 😃
