### ISSUE TITLE
All line items disappear, when trying to delete single line

### ISSUE THREAD

**Issue by pdxdiaperbank** [rubyforgood/partner#86]
**I received the following feedback from one of our partner agencies when trying to submit a diaper request via PartnerBase:** 

_"I tried to remove one line item it made my entire order disappear so I just entered it again. I clicked on wipes or something and it has an option to remove but it made everything go away."_ 

**Here is a link to the video he sent me demonstrating the issue:** 
https://www.dropbox.com/s/is9y7ypft9w3r22/IMG_0597.mov?dl=0

**Comment by chaserx** [comment]
I'll see if I can reproduce that locally

**Comment by chaserx** [comment]
Verified bug.

**Comment by chaserx** [comment]
it looks like the new page is reloading. `event.preventDefault()` isn't working possibly.
