### ISSUE TITLE
Expose an api to share partner information to the diaper app

### ISSUE THREAD

**Issue by davidshr10** [rubyforgood/partner#9]
For approving partners, we would like to share information about the them to the diaper app. This is done so that PII can be saved in the partner app and only fetched when necessary to approve the partner in the diaper app. 

Once the partner has requested to be approved, A diaper app admin will see the request and can approve it. This api call will be made by the diaper app on that GET request (https://github.com/rubyforgood/diaper/blob/master/app/views/partners/approve_partner.html.erb)

`Given` the partner has filled out the partner details
`When` a request comes in at `api/v1/partners/:diaper_partner_id`
`Then` the api will respond with the partner details with the following information

---
**Agency Information**
  - Name:
  - Distributor Type
  - Agency Type:
  - Proof of Agency Status (Link)
  - Agency Mission:
  - Address
  - Address
  - City:
  - State:
  - Zip Code:

**Media Information**
  - Website:
  - Facebook:
  - Twitter:

**Agency Stability**
  - Founded
  - Form 990:
  - Form 990 Link
  - Program Name
  - Program Description
  - Program Age
  - Case Management:
  - Evidence Based:
  - Evidence Based Description:
  - Program Client Improvement:
  - Diaper Use:
  - Other Diaper Use:
  - Currently Provide Diapers:
  - Turn Away Child Care:

  *Program Address*
  - Program Address:
  - Program Address:
  - Program City:
  - Program State:
  - Program Zip Code:

**Organizational Capacity**
  - Max Serve
  - Incorporate Plan:
  - Responsible Staff Position:
  - Storage Space:
  - Storage Space Description:
  - Trusted Pickup:

**Population Served**
  - Income Requirement Description:
  - Serve Income Circumstances:
  - Income Verification:
  - Internal DB:
  - MAAC:

  *Ethnic Composition of Those Served*
  - African American:
  - Caucasian:
  - Hispanic:
  - Asian:
  - American Indian:
  - Pacific Island:
  - Multi-Racial:
  - Other:

  *Zip Codes Served*
  - Zips:

  *Poverty Information of Those Served*
  - At FPL or Below:
  - Above 1-2 times FPL:
  - Greater 2 times FPL:
  - Poverty Unknown:

  *Ages Served*
  - Ages:

**Executive Director**
  - Executive Director Name:
  - Executive Director Phone:
  - Executive Director Email:

**Program Contact Person**
  - Program Contact Name:
  - Program Contact Phone:
  - Program Contact Mobile:
  - Program Contact Email:

**Diaper Pick Up Person**
  - Pick Up Method:
  - Pick Up Name:
  - Pick Up Phone:
  - Pick Up Email:

**Agency Distribution Information**
  - Distribution Times:
  - New Client Times:
  - More Docs Required:

**Sources of Funding**
  - Sources of Funding:
  - Sources of Diapers:
  - Diaper Budget:
  - Diaper Funding Source:
---

**Comment by vikasnautiyal** [comment]
Hi @davidshr10, I found the project exciting. Looking forward to contribute, it would be great if you could point me a good place to start from. Thanks.

**Comment by mclintprojects** [comment]
Hello @davidshr10, I'd like to take this up if no one has been assigned to it yet. Please assign me if no one has started work on it.

**Comment by vikasnautiyal** [comment]
Thank-you @davidshr10 Looking forward to contribute.

**Comment by vikasnautiyal** [comment]
Hi @davidshr10, I am sorry could not pick it up this weekend, got busy. feel free to assign it to someone who can work on it before I start working.

**Comment by seanmarcia** [comment]
Hey @vikasnautiyal any updates on this? We're having a hack day tomorrow and will try and pick it up if you haven't made any progress.
