### ISSUE TITLE
Add testing information in ReadMe

### ISSUE THREAD

**Issue by Nirvikalpa108** [rubyforgood/partner#91]
Hi guys, as I was trying to run the capybara tests I realised that the information to do this was on the [Diaper ReadMe](https://github.com/rubyforgood/diaper#testing), but not here on the Partner repo. Do you think we should add a link on the Partner repo to the Diaper ReadMe testing section? Great to learn your view on this.
Thank you so much 😃

**Comment by benreyn** [comment]
Yes! Thank you @Nirvikalpa108! I think the right approach here is probably to just improve our own ReadMe to be as thorough as Diaperbase's rather than linking off to their ReadMe.

**Comment by benreyn** [comment]
Closed in #153
