### ISSUE TITLE
Capture "other" agency type description

### ISSUE THREAD

**Issue by chaserx** [rubyforgood/partner#92]
Related to #75 and #90 

We now restrict the user's selection of agency types to a defined list, but we need to also capture some description from the user when they select the "other" agency type. 

Add an input that's hidden by default and displayed on "other" selection in the agency type dropdown menu.

**Comment by chaserx** [comment]
@Nirvikalpa108 here's this one that to follow #75 and #90

**Comment by Nirvikalpa108** [comment]
Great, looking forward to tackling this! Thanks @chaserx
