### ISSUE TITLE
RSpec: Make sure partners_controller_spec.rb tests both html and json

### ISSUE THREAD

**Issue by NiquiCara** [rubyforgood/partner#98]
This issue is work remaining from #51.
# Controllers
## partners_controller_spec.rb
(Note: html specs seem implemented; but not Json?)

  - [ ] :create is successful via HTML
  - [x] :create is successful via JSON
  - [ ] :update is successful via HTML
  - [x] :update is successful via JSON

**Comment by gdombchik** [comment]
The json was removed as part of issue 50:  Remove all json endpoints that are not in the api.

**Comment by benreyn** [comment]
Good catch @gdombchik. Closing as no longer applicable.
