### ISSUE TITLE
RSpec: Test API behavior with/without API keys

### ISSUE THREAD

**Issue by NiquiCara** [rubyforgood/partner#99]
This issue is work remaining from #51.
# API
## partners_controller_spec.rb
(note: not sure if implemented.. perhaps in spec/requests/api/v1/partners_requests_spec.rb ???)

  - [ ] :create returns :forbidden if the API key is invalid
 - [ ] :create is successful
 - [ ] :update returns :forbidden if the API key is invalid
 - [ ] :update is successful
 - [ ] :show returns :forbidden if the API key is invalid
 - [ ] :show is successful

**Comment by samudary** [comment]
🖐️ I can tackle this
